name: CI Pipeline

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  lint:
    name: Lint Codebase
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18' 

      - run: npm install

      - name: Run Linter
        run: npm run lint

  type-check:
    name: Type Check Codebase
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18' 

      - run: npm install

      - name: Run TypeScript Type Checking
        run: npm run type-check

  format:
    name: Check Code Formatting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Use Node.js 18 or newer

      - run: npm install

      - name: Check Formatting
        run: npm run fmt --check

        
  testing:
    name: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Use Node.js 18 or newer

      - run: npm install

      - name: Run tests
        run: npm run test:ci
        
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Generate OpenAPI
        run: ./generate-openapi.sh
      - name: Run Tests
        run: npm test

